<Project Sdk="Microsoft.NET.Sdk">

   	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<RootNamespace>nah_the_search</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
    </PropertyGroup>

	<ItemGroup>
	  <Content Include="Tools\**\*">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>
